### ISSUE TITLE
Log application errors in Sentry

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-feedback#67]
As a system owner,  I want to see errors show up in sentry.

- Need to log a users username, station id and email address. Look at eFolder Express for this.

### Technical notes
- This will need to be verified by me or Alan, and will also require one of us to integrate it.
- This is already working in the other apps, use them as reference

**Comment by anyakhvost** [comment]
This can only be tested in UAT or production. We also need to set SENTRY_DSN in Feedback.

**Comment by shanear** [comment]
This is failing because of an SSL error :(

I think this will require us to add the VA CA to our deployment scripts

```
** [Raven] Sending event 24c01d83e6b46109fabcb04c0497e434 to Sentry
** [Raven] Sending event 24c01d83e6b46109fabcb04c0497e434 to Sentry
** [Raven] Raven HTTP Transport connecting to https://sentry.ds.va.gov
** [Raven] Raven HTTP Transport connecting to https://sentry.ds.va.gov
** [Raven] Unable to record event with remote Sentry server (Faraday::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed)
** [Raven] Unable to record event with remote Sentry server (Faraday::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed)
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
** [Raven] /opt/rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
** [Raven] /opt/caseflow-feedback/src/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
** [Raven] Failed to submit event: RuntimeError: Shane's test error
** [Raven] Failed to submit event: RuntimeError: Shane's test error
```

**Comment by anyakhvost** [comment]
Added the certificate.

**Comment by shanear** [comment]
<img width="1554" alt="screen shot 2017-01-05 at 4 41 00 pm" src="https://cloud.githubusercontent.com/assets/1596259/21698628/ccd6811e-d365-11e6-97bb-d874d84aefee.png">

works! 🎉
